### PR TITLE
added a ascii art

### PR DESCRIPTION
**Pull request by AyushRajSharma**
I love this feature.

### CODE REVIEW

**Comment by aherd2985** [comment]
If you would like to add python scripts to the repo, can you add the functionality to call the scripts from the Console Application?

Check out this link for integrating Python scripts with C#.
https://stackoverflow.com/questions/11779143/how-do-i-run-a-python-script-from-c

You can download Visual Studio Code for free and open the .csproj file for building/testing.
https://code.visualstudio.com/

Please let me know if you have any questions or concerns, thanks!

**Comment by AyushRajSharma** [comment]
> If you would like to add python scripts to the repo, can you add the functionality to call the scripts from the Console Application?
> 
> Check out this link for integrating Python scripts with C#.
> https://stackoverflow.com/questions/11779143/how-do-i-run-a-python-script-from-c
> 
> You can download Visual Studio Code for free and open the .csproj file for building/testing.
> https://code.visualstudio.com/
> 
> Please let me know if you have any questions or concerns, thanks!

i am not able to understand the functionality to call the scripts from the console Application.
i use pycharm for coding every time when i run the python script it give result in console.
can you help me to understand so that i can complete it ?

**Comment by AyushRajSharma** [comment]
can i get your contacts for query!

**Comment by aherd2985** [comment]
I don't see your email but my website displays a few ways to message me:
https://technoherder.com/consultingFull.php

This is a Visual Studio solution for a C# Console Application.  

You can download Visual Studio Code for free and open the .csproj file for building/testing.
https://code.visualstudio.com/

When the executable runs, it opens a terminal and executes the code.  Adding a python script to the repo is not adding to the project itself.

Please find a way to execute the script from C#; the easiest way would be to add a new method in the Program.cs file.

The following StackOverflow link has some ideas that could be helpful, or use Google to find another solution.
https://stackoverflow.com/questions/11779143/how-do-i-run-a-python-script-from-c

This is not a repo for pycharm, please use Visual Studio.

Thank you!

**Comment by kolya5544** [comment]
Implemented in #17

**Comment by AyushRajSharma** [comment]
i hope now it is fine. if there is some issue with it please let me know.
this is my first c# application and i love it.
Thank you.

**Review by aherd2985 — APPROVED** [review]

**Pull request merged**
