### PR TITLE
Case 21 GenderFromName

### PR DESCRIPTION
**Pull request by IrvinDominin**

### CODE REVIEW

**Comment by IrvinDominin** [comment]
Can I ask you to set the Hacktoberfest tag to the PR and commits please @aherd2985 ?

**Review by aherd2985 — APPROVED** [review]

**Comment by aherd2985** [comment]
I labeled all the PR's for Hacktoberfest, not sure I can do the commits like that.

Per the rules, they should be good, but let me know if it needs anything else, thanks!

**Comment by IrvinDominin** [comment]
@aherd2985 rules described here: https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by aherd2985** [comment]
They should be getting counted.

The repo has the label hactoberfest.

I did switch over the label from hacktoberfest to hacktoberfest-accepted to make sure it is counted in every way.

Let me know if it needs any changes, thanks!

PRs count if:
Submitted during the month of October AND (
  The PR is labelled as hacktoberfest-accepted by a maintainer OR
  Submitted in a repo with the hacktoberfest topic AND (
    The PR is merged OR
    The PR has been approved
  )
)
________________________________

**Pull request merged**
