### PR TITLE
Code beautifying

### PR DESCRIPTION
**Pull request by kolya5544**
- Added #region to group parts of code
- Fixed spacing once again (perhaps our IDEs are different?)
- Documented all port scanner functions as well as optimized parts of its code

### CODE REVIEW

**Review by aherd2985 — APPROVED** [review]
Making code easier to read is a tremendous help, thank you!
After October, I'd like to help out on some of your projects; I have a feeling this repo is going to keep me busy this month.

**Comment by kolya5544** [comment]
> Making code easier to read is a tremendous help, thank you!
> After October, I'd like to help out on some of your projects; I have a feeling this repo is going to keep me busy this month.

That would be nice, thank you! I'd like to keep `FreeNet` only developed by me though. I would really appreciate help on HSMODS and BearFTP

**Comment by aherd2985** [comment]
Sounds great; I was already poking around in BearFTP, this looks really useful!

**Comment by kolya5544** [comment]
We can coordinate better in code changes to this project, if you have Discord/other instant chat.

**Pull request merged**
