### PR TITLE
Removed unused imports from Program.cs & Models; Fixed formatting

### PR DESCRIPTION
**Pull request by hariharansubramanian**
This PR addresses issue #23 fixing all unused imports and some minor formatting.

### CODE REVIEW

**Review by aherd2985 — APPROVED** [review]

**Comment by hariharansubramanian** [comment]
Im not sure what the above conflicts are?
I down-merged the latest master into my local branch, and I have no merge conflicts

Do let me know how i can go about resolving these merge conflicts

**Comment by aherd2985** [comment]
There has been a lot of activity on the repo and I am still getting through my first cup of coffee.

Project is healthy and running; thank you for your help and improvements on the repo!

**Comment by hariharansubramanian** [comment]
@aherd2985 My bad, I was doing it all wrong - first time working with forked repos.
I down-merged the latest master branch of the forked repository into the local branch, which obviously resulted in no conflicts.
lesson learnt.

Love this fun application, will publish new option features soon!

**Comment by aherd2985** [comment]
No worries, I’m learning every day too.

I’m glad to hear you like the project and I’m looking forward to your next feature!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request merged**
