### PR TITLE
More information from countries 

### PR DESCRIPTION
**Pull request by jperaza1**
New information was added to the countries, the country option was added to the menu and the reference to the generic lists "System.Collections.Generic" was added.

### CODE REVIEW

**Review by aherd2985 — APPROVED** [review]
Thank you!

**Comment by aherd2985** [comment]
I resolved the merge conflicts.

Please update and/or grab the latest version, thank you!

**Comment by jperaza1** [comment]
Hey i have a question
I complete the 4 PR but i see the next messages
Project maintainers now have a week to review your contributions.

**Comment by aherd2985** [comment]
Your pull requests were reviewed and approved. DigitalOcean has a mandatory probationary period; I don’t believe there is a way to fast track it.
Please let know if there is anything else I can do to help, thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request merged**
